export const CarsData = [
  { imageUrl: "/images/Rectangle 4.png", name: "Land rover",type:"manual",category:"SUV", price: "40,000", description: "Rwanda is a hidden gem! the landscape orporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas " },
  { imageUrl: "/images/Rectangle 4.png", name: "Land rover",type:"automatic",category:"SUV", price: "40,000", description: "Rwanda is a hidden gem! the landscape orporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas " },
  { imageUrl: "/images/Rectangle 4.png", name: "Land rover",type:"manual",category:"SUV", price: "40,000", description: "Rwanda is a hidden gem! the landscape orporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas " },
  { imageUrl: "/images/Rectangle 4.png", name: "Land rover",type:"manual",category:"SUV", price: "40,000", description: "Rwanda is a hidden gem! the landscape orporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas " },
  { imageUrl: "/images/Rectangle 4.png", name: "Land rover",type:"manual",category:"SUV", price: "40,000", description: "Rwanda is a hidden gem! the landscape orporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas " },
  { imageUrl: "/images/Rectangle 4.png", name: "Land rover",type:"manual",category:"SUV", price: "40,000", description: "Rwanda is a hidden gem! the landscape orporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas " },
  { imageUrl: "/images/Rectangle 4.png", name: "Land rover",type:"manual",category:"SUV", price: "40,000", description: "Rwanda is a hidden gem! the landscape orporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas " },
  { imageUrl: "/images/Rectangle 4.png", name: "Land rover",type:"manual",category:"SUV", price: "40,000", description: "Rwanda is a hidden gem! the landscape orporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas " },
  { imageUrl: "/images/Rectangle 4.png", name: "Land rover",type:"manual",category:"SUV", price: "40,000", description: "Rwanda is a hidden gem! the landscape orporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas " },
  { imageUrl: "/images/Rectangle 4.png", name: "Land rover",type:"manual",category:"SUV", price: "40,000", description: "Rwanda is a hidden gem! the landscape orporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas " },
  
]